# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

before_script:
  - wget https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip
  - unzip google_appengine_1.8.9.zip

install:
  - pip install coveralls

script:
  - export PYTHONPATH=$PYTHONPATH:${PWD}/google_appengine
  - coverage run manage.py core appengine_sessions

after_success:
  - coveralls
