# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

before_script:
  - wget https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
  - unzip -q google_appengine_1.8.9.zip
  - mysql -e 'create database badmovieknights;'

install:
  - pip install coveralls
  - pip install MySQL-python
  - pip install mock

script:
  - export PATH=${PWD}/google_appengine:$PATH
  - coverage run --omit="*/migrations/*,*/test*" --source=core,blog,api,c3po manage.py test core blog api c3po --settings=badmovieknights.travis_settings

after_success:
  - coveralls
